<?php
/**
 * FileuploadApi
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * xpan
 *
 * xpanapi
 *
 * The version of the OpenAPI document: 0.1
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.0.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use OpenAPI\Client\ApiException;
use OpenAPI\Client\Configuration;
use OpenAPI\Client\HeaderSelector;
use OpenAPI\Client\ObjectSerializer;

/**
 * FileuploadApi Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class FileuploadApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex)
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation pcssuperfile2
     *
     * This operation contains host(s) defined in the OpenAP spec. Use 'hostIndex' to select the host.
     * URL: https://d.pcs.baidu.com
     *
     * @param  string $access_token access_token (required)
     * @param  string $partseq partseq (required)
     * @param  string $path path (required)
     * @param  string $uploadid uploadid (required)
     * @param  string $type type (required)
     * @param  \SplFileObject $file 要进行传送的本地文件分片 (optional)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return string
     */
    public function pcssuperfile2($access_token, $partseq, $path, $uploadid, $type, $file = null)
    {
        list($response) = $this->pcssuperfile2WithHttpInfo($access_token, $partseq, $path, $uploadid, $type, $file);
        return $response;
    }

    /**
     * Operation pcssuperfile2WithHttpInfo
     *
     * This operation contains host(s) defined in the OpenAP spec. Use 'hostIndex' to select the host.
     * URL: https://d.pcs.baidu.com
     *
     * @param  string $access_token (required)
     * @param  string $partseq (required)
     * @param  string $path (required)
     * @param  string $uploadid (required)
     * @param  string $type (required)
     * @param  \SplFileObject $file 要进行传送的本地文件分片 (optional)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of string, HTTP status code, HTTP response headers (array of strings)
     */
    public function pcssuperfile2WithHttpInfo($access_token, $partseq, $path, $uploadid, $type, $file = null)
    {
        $request = $this->pcssuperfile2Request($access_token, $partseq, $path, $uploadid, $type, $file);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('string' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, 'string', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = 'string';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'string',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation pcssuperfile2Async
     *
     * This operation contains host(s) defined in the OpenAP spec. Use 'hostIndex' to select the host.
     * URL: https://d.pcs.baidu.com
     *
     * @param  string $access_token (required)
     * @param  string $partseq (required)
     * @param  string $path (required)
     * @param  string $uploadid (required)
     * @param  string $type (required)
     * @param  \SplFileObject $file 要进行传送的本地文件分片 (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function pcssuperfile2Async($access_token, $partseq, $path, $uploadid, $type, $file = null)
    {
        return $this->pcssuperfile2AsyncWithHttpInfo($access_token, $partseq, $path, $uploadid, $type, $file)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation pcssuperfile2AsyncWithHttpInfo
     *
     * This operation contains host(s) defined in the OpenAP spec. Use 'hostIndex' to select the host.
     * URL: https://d.pcs.baidu.com
     *
     * @param  string $access_token (required)
     * @param  string $partseq (required)
     * @param  string $path (required)
     * @param  string $uploadid (required)
     * @param  string $type (required)
     * @param  \SplFileObject $file 要进行传送的本地文件分片 (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function pcssuperfile2AsyncWithHttpInfo($access_token, $partseq, $path, $uploadid, $type, $file = null)
    {
        $returnType = 'string';
        $request = $this->pcssuperfile2Request($access_token, $partseq, $path, $uploadid, $type, $file);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'pcssuperfile2'
     *
     * This operation contains host(s) defined in the OpenAP spec. Use 'hostIndex' to select the host.
     * URL: https://d.pcs.baidu.com
     *
     * @param  string $access_token (required)
     * @param  string $partseq (required)
     * @param  string $path (required)
     * @param  string $uploadid (required)
     * @param  string $type (required)
     * @param  \SplFileObject $file 要进行传送的本地文件分片 (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function pcssuperfile2Request($access_token, $partseq, $path, $uploadid, $type, $file = null)
    {
        // verify the required parameter 'access_token' is set
        if ($access_token === null || (is_array($access_token) && count($access_token) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $access_token when calling pcssuperfile2'
            );
        }
        // verify the required parameter 'partseq' is set
        if ($partseq === null || (is_array($partseq) && count($partseq) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $partseq when calling pcssuperfile2'
            );
        }
        // verify the required parameter 'path' is set
        if ($path === null || (is_array($path) && count($path) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $path when calling pcssuperfile2'
            );
        }
        // verify the required parameter 'uploadid' is set
        if ($uploadid === null || (is_array($uploadid) && count($uploadid) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $uploadid when calling pcssuperfile2'
            );
        }
        // verify the required parameter 'type' is set
        if ($type === null || (is_array($type) && count($type) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $type when calling pcssuperfile2'
            );
        }

        $resourcePath = '/rest/2.0/pcs/superfile2?method=upload&openapi=xpansdk';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $access_token,
            'access_token', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?: []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $partseq,
            'partseq', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?: []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $path,
            'path', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?: []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $uploadid,
            'uploadid', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?: []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $type,
            'type', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?: []);



        // form params
        if ($file !== null) {
            $multipart = true;
            $formParams['file'] = [];
            $paramFiles = is_array($file) ? $file : [$file];
            foreach ($paramFiles as $paramFile) {
                $formParams['file'][] = \GuzzleHttp\Psr7\Utils::tryFopen(
                    ObjectSerializer::toFormValue($paramFile),
                    'rb'
                );
            }
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['text/html;charset=utf8']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['text/html;charset=utf8'],
                ['multipart/form-data']
            );
        }

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHosts = ["https://d.pcs.baidu.com"];
        if ($this->hostIndex < 0 || $this->hostIndex >= sizeof($operationHosts)) {
            throw new \InvalidArgumentException("Invalid index {$this->hostIndex} when selecting the host. Must be less than ".sizeof($operationHosts));
        }
        $operationHost = $operationHosts[$this->hostIndex];

        $query = ObjectSerializer::buildQuery($queryParams);

        $separator = '?';
        if (strchr($resourcePath, "?") !== false) {
            $separator = '&';
        }
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "{$separator}{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation xpanfilecreate
     *
     * This operation contains host(s) defined in the OpenAP spec. Use 'hostIndex' to select the host.
     * URL: https://pan.baidu.com
     *
     * @param  string $access_token access_token (required)
     * @param  string $path 与precreate的path值保持一致 (required)
     * @param  int $isdir isdir (required)
     * @param  int $size 与precreate的size值保持一致 (required)
     * @param  string $uploadid precreate返回的uploadid (required)
     * @param  string $block_list 与precreate的block_list值保持一致 (required)
     * @param  int $rtype rtype (optional)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\Filecreateresponse
     */
    public function xpanfilecreate($access_token, $path, $isdir, $size, $uploadid, $block_list, $rtype = null)
    {
        list($response) = $this->xpanfilecreateWithHttpInfo($access_token, $path, $isdir, $size, $uploadid, $block_list, $rtype);
        return $response;
    }

    /**
     * Operation xpanfilecreateWithHttpInfo
     *
     * This operation contains host(s) defined in the OpenAP spec. Use 'hostIndex' to select the host.
     * URL: https://pan.baidu.com
     *
     * @param  string $access_token (required)
     * @param  string $path 与precreate的path值保持一致 (required)
     * @param  int $isdir isdir (required)
     * @param  int $size 与precreate的size值保持一致 (required)
     * @param  string $uploadid precreate返回的uploadid (required)
     * @param  string $block_list 与precreate的block_list值保持一致 (required)
     * @param  int $rtype rtype (optional)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\Filecreateresponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function xpanfilecreateWithHttpInfo($access_token, $path, $isdir, $size, $uploadid, $block_list, $rtype = null)
    {
        $request = $this->xpanfilecreateRequest($access_token, $path, $isdir, $size, $uploadid, $block_list, $rtype);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\OpenAPI\Client\Model\Filecreateresponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Model\Filecreateresponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\Filecreateresponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\OpenAPI\Client\Model\Filecreateresponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\Filecreateresponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation xpanfilecreateAsync
     *
     * This operation contains host(s) defined in the OpenAP spec. Use 'hostIndex' to select the host.
     * URL: https://pan.baidu.com
     *
     * @param  string $access_token (required)
     * @param  string $path 与precreate的path值保持一致 (required)
     * @param  int $isdir isdir (required)
     * @param  int $size 与precreate的size值保持一致 (required)
     * @param  string $uploadid precreate返回的uploadid (required)
     * @param  string $block_list 与precreate的block_list值保持一致 (required)
     * @param  int $rtype rtype (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function xpanfilecreateAsync($access_token, $path, $isdir, $size, $uploadid, $block_list, $rtype = null)
    {
        return $this->xpanfilecreateAsyncWithHttpInfo($access_token, $path, $isdir, $size, $uploadid, $block_list, $rtype)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation xpanfilecreateAsyncWithHttpInfo
     *
     * This operation contains host(s) defined in the OpenAP spec. Use 'hostIndex' to select the host.
     * URL: https://pan.baidu.com
     *
     * @param  string $access_token (required)
     * @param  string $path 与precreate的path值保持一致 (required)
     * @param  int $isdir isdir (required)
     * @param  int $size 与precreate的size值保持一致 (required)
     * @param  string $uploadid precreate返回的uploadid (required)
     * @param  string $block_list 与precreate的block_list值保持一致 (required)
     * @param  int $rtype rtype (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function xpanfilecreateAsyncWithHttpInfo($access_token, $path, $isdir, $size, $uploadid, $block_list, $rtype = null)
    {
        $returnType = '\OpenAPI\Client\Model\Filecreateresponse';
        $request = $this->xpanfilecreateRequest($access_token, $path, $isdir, $size, $uploadid, $block_list, $rtype);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'xpanfilecreate'
     *
     * This operation contains host(s) defined in the OpenAP spec. Use 'hostIndex' to select the host.
     * URL: https://pan.baidu.com
     *
     * @param  string $access_token (required)
     * @param  string $path 与precreate的path值保持一致 (required)
     * @param  int $isdir isdir (required)
     * @param  int $size 与precreate的size值保持一致 (required)
     * @param  string $uploadid precreate返回的uploadid (required)
     * @param  string $block_list 与precreate的block_list值保持一致 (required)
     * @param  int $rtype rtype (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function xpanfilecreateRequest($access_token, $path, $isdir, $size, $uploadid, $block_list, $rtype = null)
    {
        // verify the required parameter 'access_token' is set
        if ($access_token === null || (is_array($access_token) && count($access_token) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $access_token when calling xpanfilecreate'
            );
        }
        // verify the required parameter 'path' is set
        if ($path === null || (is_array($path) && count($path) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $path when calling xpanfilecreate'
            );
        }
        // verify the required parameter 'isdir' is set
        if ($isdir === null || (is_array($isdir) && count($isdir) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $isdir when calling xpanfilecreate'
            );
        }
        // verify the required parameter 'size' is set
        if ($size === null || (is_array($size) && count($size) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $size when calling xpanfilecreate'
            );
        }
        // verify the required parameter 'uploadid' is set
        if ($uploadid === null || (is_array($uploadid) && count($uploadid) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $uploadid when calling xpanfilecreate'
            );
        }
        // verify the required parameter 'block_list' is set
        if ($block_list === null || (is_array($block_list) && count($block_list) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $block_list when calling xpanfilecreate'
            );
        }

        $resourcePath = '/rest/2.0/xpan/file?method=create&openapi=xpansdk';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $access_token,
            'access_token', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?: []);



        // form params
        if ($path !== null) {
            $formParams['path'] = ObjectSerializer::toFormValue($path);
        }
        // form params
        if ($isdir !== null) {
            $formParams['isdir'] = ObjectSerializer::toFormValue($isdir);
        }
        // form params
        if ($size !== null) {
            $formParams['size'] = ObjectSerializer::toFormValue($size);
        }
        // form params
        if ($uploadid !== null) {
            $formParams['uploadid'] = ObjectSerializer::toFormValue($uploadid);
        }
        // form params
        if ($block_list !== null) {
            $formParams['block_list'] = ObjectSerializer::toFormValue($block_list);
        }
        // form params
        if ($rtype !== null) {
            $formParams['rtype'] = ObjectSerializer::toFormValue($rtype);
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json; charset=UTF-8']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json; charset=UTF-8'],
                ['application/x-www-form-urlencoded']
            );
        }

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHosts = ["https://pan.baidu.com"];
        if ($this->hostIndex < 0 || $this->hostIndex >= sizeof($operationHosts)) {
            throw new \InvalidArgumentException("Invalid index {$this->hostIndex} when selecting the host. Must be less than ".sizeof($operationHosts));
        }
        $operationHost = $operationHosts[$this->hostIndex];

        $query = ObjectSerializer::buildQuery($queryParams);

        $separator = '?';
        if (strchr($resourcePath, "?") !== false) {
            $separator = '&';
        }
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "{$separator}{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation xpanfileprecreate
     *
     * This operation contains host(s) defined in the OpenAP spec. Use 'hostIndex' to select the host.
     * URL: https://pan.baidu.com
     *
     * @param  string $access_token access_token (required)
     * @param  string $path 对于一般的第三方软件应用，路径以 \\\&quot;/apps/your-app-name/\\\&quot; 开头。对于小度等硬件应用，路径一般 \\\&quot;/来自：小度设备/\\\&quot; 开头。对于定制化配置的硬件应用，根据配置情况进行填写。 (required)
     * @param  int $isdir isdir (required)
     * @param  int $size size (required)
     * @param  int $autoinit autoinit (required)
     * @param  string $block_list 由MD5字符串组成的list (required)
     * @param  int $rtype rtype (optional)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\Fileprecreateresponse
     */
    public function xpanfileprecreate($access_token, $path, $isdir, $size, $autoinit, $block_list, $rtype = null)
    {
        list($response) = $this->xpanfileprecreateWithHttpInfo($access_token, $path, $isdir, $size, $autoinit, $block_list, $rtype);
        return $response;
    }

    /**
     * Operation xpanfileprecreateWithHttpInfo
     *
     * This operation contains host(s) defined in the OpenAP spec. Use 'hostIndex' to select the host.
     * URL: https://pan.baidu.com
     *
     * @param  string $access_token (required)
     * @param  string $path 对于一般的第三方软件应用，路径以 \\\&quot;/apps/your-app-name/\\\&quot; 开头。对于小度等硬件应用，路径一般 \\\&quot;/来自：小度设备/\\\&quot; 开头。对于定制化配置的硬件应用，根据配置情况进行填写。 (required)
     * @param  int $isdir isdir (required)
     * @param  int $size size (required)
     * @param  int $autoinit autoinit (required)
     * @param  string $block_list 由MD5字符串组成的list (required)
     * @param  int $rtype rtype (optional)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\Fileprecreateresponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function xpanfileprecreateWithHttpInfo($access_token, $path, $isdir, $size, $autoinit, $block_list, $rtype = null)
    {
        $request = $this->xpanfileprecreateRequest($access_token, $path, $isdir, $size, $autoinit, $block_list, $rtype);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\OpenAPI\Client\Model\Fileprecreateresponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Model\Fileprecreateresponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\Fileprecreateresponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\OpenAPI\Client\Model\Fileprecreateresponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\Fileprecreateresponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation xpanfileprecreateAsync
     *
     * This operation contains host(s) defined in the OpenAP spec. Use 'hostIndex' to select the host.
     * URL: https://pan.baidu.com
     *
     * @param  string $access_token (required)
     * @param  string $path 对于一般的第三方软件应用，路径以 \\\&quot;/apps/your-app-name/\\\&quot; 开头。对于小度等硬件应用，路径一般 \\\&quot;/来自：小度设备/\\\&quot; 开头。对于定制化配置的硬件应用，根据配置情况进行填写。 (required)
     * @param  int $isdir isdir (required)
     * @param  int $size size (required)
     * @param  int $autoinit autoinit (required)
     * @param  string $block_list 由MD5字符串组成的list (required)
     * @param  int $rtype rtype (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function xpanfileprecreateAsync($access_token, $path, $isdir, $size, $autoinit, $block_list, $rtype = null)
    {
        return $this->xpanfileprecreateAsyncWithHttpInfo($access_token, $path, $isdir, $size, $autoinit, $block_list, $rtype)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation xpanfileprecreateAsyncWithHttpInfo
     *
     * This operation contains host(s) defined in the OpenAP spec. Use 'hostIndex' to select the host.
     * URL: https://pan.baidu.com
     *
     * @param  string $access_token (required)
     * @param  string $path 对于一般的第三方软件应用，路径以 \\\&quot;/apps/your-app-name/\\\&quot; 开头。对于小度等硬件应用，路径一般 \\\&quot;/来自：小度设备/\\\&quot; 开头。对于定制化配置的硬件应用，根据配置情况进行填写。 (required)
     * @param  int $isdir isdir (required)
     * @param  int $size size (required)
     * @param  int $autoinit autoinit (required)
     * @param  string $block_list 由MD5字符串组成的list (required)
     * @param  int $rtype rtype (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function xpanfileprecreateAsyncWithHttpInfo($access_token, $path, $isdir, $size, $autoinit, $block_list, $rtype = null)
    {
        $returnType = '\OpenAPI\Client\Model\Fileprecreateresponse';
        $request = $this->xpanfileprecreateRequest($access_token, $path, $isdir, $size, $autoinit, $block_list, $rtype);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'xpanfileprecreate'
     *
     * This operation contains host(s) defined in the OpenAP spec. Use 'hostIndex' to select the host.
     * URL: https://pan.baidu.com
     *
     * @param  string $access_token (required)
     * @param  string $path 对于一般的第三方软件应用，路径以 \\\&quot;/apps/your-app-name/\\\&quot; 开头。对于小度等硬件应用，路径一般 \\\&quot;/来自：小度设备/\\\&quot; 开头。对于定制化配置的硬件应用，根据配置情况进行填写。 (required)
     * @param  int $isdir isdir (required)
     * @param  int $size size (required)
     * @param  int $autoinit autoinit (required)
     * @param  string $block_list 由MD5字符串组成的list (required)
     * @param  int $rtype rtype (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function xpanfileprecreateRequest($access_token, $path, $isdir, $size, $autoinit, $block_list, $rtype = null)
    {
        // verify the required parameter 'access_token' is set
        if ($access_token === null || (is_array($access_token) && count($access_token) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $access_token when calling xpanfileprecreate'
            );
        }
        // verify the required parameter 'path' is set
        if ($path === null || (is_array($path) && count($path) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $path when calling xpanfileprecreate'
            );
        }
        // verify the required parameter 'isdir' is set
        if ($isdir === null || (is_array($isdir) && count($isdir) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $isdir when calling xpanfileprecreate'
            );
        }
        // verify the required parameter 'size' is set
        if ($size === null || (is_array($size) && count($size) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $size when calling xpanfileprecreate'
            );
        }
        // verify the required parameter 'autoinit' is set
        if ($autoinit === null || (is_array($autoinit) && count($autoinit) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $autoinit when calling xpanfileprecreate'
            );
        }
        // verify the required parameter 'block_list' is set
        if ($block_list === null || (is_array($block_list) && count($block_list) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $block_list when calling xpanfileprecreate'
            );
        }

        $resourcePath = '/rest/2.0/xpan/file?method=precreate&openapi=xpansdk';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $access_token,
            'access_token', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?: []);



        // form params
        if ($path !== null) {
            $formParams['path'] = ObjectSerializer::toFormValue($path);
        }
        // form params
        if ($isdir !== null) {
            $formParams['isdir'] = ObjectSerializer::toFormValue($isdir);
        }
        // form params
        if ($size !== null) {
            $formParams['size'] = ObjectSerializer::toFormValue($size);
        }
        // form params
        if ($autoinit !== null) {
            $formParams['autoinit'] = ObjectSerializer::toFormValue($autoinit);
        }
        // form params
        if ($block_list !== null) {
            $formParams['block_list'] = ObjectSerializer::toFormValue($block_list);
        }
        // form params
        if ($rtype !== null) {
            $formParams['rtype'] = ObjectSerializer::toFormValue($rtype);
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json; charset=UTF-8']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json; charset=UTF-8'],
                ['application/x-www-form-urlencoded']
            );
        }

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHosts = ["https://pan.baidu.com"];
        if ($this->hostIndex < 0 || $this->hostIndex >= sizeof($operationHosts)) {
            throw new \InvalidArgumentException("Invalid index {$this->hostIndex} when selecting the host. Must be less than ".sizeof($operationHosts));
        }
        $operationHost = $operationHosts[$this->hostIndex];

        $query = ObjectSerializer::buildQuery($queryParams);
        $separator = '?';
        if (strchr($resourcePath, "?") !== false) {
            $separator = '&';
        }
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "{$separator}{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
